accessible: false
name: LINFO1121-0822
description: ''
admins:
- pschaus
tutors: []
groups_student_choice: false
allow_unregister: true
allow_preview: false
registration: true
registration_password: null
registration_ac: null
registration_ac_list: []
is_lti: false
lti_url: ''
lti_keys: {{}}
lti_send_back_grade: false
task_dispenser: combinatory_test
dispenser_data: {}
